AWSTemplateFormatVersion: "2010-09-09"
Description: 'DNS entries for using mailbox.org als mailprovider for a domain hosted in Route53. Entries are set according to https://kb.mailbox.org/display/BMBOKB/E-Mail-Adressen+der+eigenen+Domain+nutzen'

Parameters:
  DomainName:
    Type: String
    Description: Name of the domain, without a `.` at the end, e.g. `example.com`
  TTL:
    Type: String
    Default: '900'
    Description: TTL for all entries in seconds (given as string)
  HostedZoneName:
    Type: String
    Description: Name of the hosted zone in Route53
    
Resources:
  MXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: MX Records for mailbox.org
      Name:
        !Sub
          - '${Domain}.'
          - { Domain: !Ref DomainName }
      Type: MX
      TTL: !Ref TTL 
      ResourceRecords:
      - '10 mxext1.mailbox.org.'
      - '10 mxext2.mailbox.org.'
      - '20 mxext3.mailbox.org.'

  SPFRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: SPF record for sending server verification
      Name:
        !Sub
          - '${Domain}.'
          - { Domain: !Ref DomainName }
      Type: TXT
      TTL: !Ref TTL 
      ResourceRecords:
      - '"v=spf1 include:mailbox.org"'

  DKIMKeyOneRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: First DKMI key for email content verification
      Name:
        !Sub
          - 'mbo0001._domainkey.${Domain}.'
          - { Domain: !Ref DomainName }
      Type: TXT
      TTL: !Ref TTL 
      ResourceRecords:
      - '"v=DKIM1; k=rsa; " "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2K4PavXoNY8eGK2u61" "LIQlOHS8f5sWsCK5b+HMOfo0M+aNHwfqlVdzi/IwmYnuDKuXYuCllrgnxZ4fG4yV" "aux58v9grVsFHdzdjPlAQfp5rkiETYpCMZwgsmdseJ4CoZaosPHLjPumFE/Ua2WA" "QQljnunsM9TONM9L6KxrO9t5IISD1XtJb0bq1lVI/e72k3mnPd/q77qzhTDmwN4T" "SNJZN8sxzUJx9HNSMRRoEIHSDLTIJUK+Up8IeCx0B7CiOzG5w/cHyZ3AM5V8lkqB" "aTDK46AwTkTVGJf59QxUZArG3FEH5vy9HzDmy0tGG+053/x4RqkhqMg5/ClDm+lp" "ZqWwIDAQAB"'

  DKIMKeyTwoRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: Second DKMI key for email content verification
      Name:
        !Sub
          - 'mbo0002._domainkey.${Domain}.'
          - { Domain: !Ref DomainName }
      Type: TXT
      TTL: !Ref TTL 
      ResourceRecords:
      - '"v=DKIM1; k=rsa; " "p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqxEKIg2c48ecfmy/+r" "j35sBOhdfIYGNDCMeHy0b36DX6MNtS7zA/VDR2q5ubtHzraL5uUGas8kb/33wtrW" "FYxierLRXy12qj8ItdYCRugu9tXTByEED05WdBtRzJmrb8YBMfeK0E0K3wwoWfhI" "k/wzKbjMkbqYBOTYLlIcVGQWzOfN7/n3n+VChfu6sGFK3k2qrJNnw22iFy4C8Ks7" "j77+tCpm0PoUwA2hOdLrRw3ldx2E9PH0GVwIMJRgekY6cS7DrbHrj/AeGlwfwwCS" "i9T23mYvc79nVrh2+82ZqmkpZSTD2qq+ukOkyjdRuUPck6e2b+x141Nzd81dIZVf" "OEiwIDAQAB"'

  DMARCRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: DMARC setting for reports on failed DKIM or SPF checks
      Name:
        !Sub
          - '_dmarc.${Domain}.'
          - { Domain: !Ref DomainName }
      Type: TXT
      TTL: !Ref TTL 
      ResourceRecords:
      - !Sub
          - '"v=DMARC1;p=none;rua=mailto:postmaster@${Domain};ruf=mailto:postmaster@${Domain}"'
          - { Domain: !Ref DomainName }

  AutoConfigCnameRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: Cname record for automatic discovery of connection settings
      Name:
        !Sub
          - 'autoconfig.${Domain}.'
          - { Domain: !Ref DomainName }
      Type: CNAME
      TTL: !Ref TTL 
      ResourceRecords:
      - 'mailbox.org.'

  AutoConfigSRVRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Comment: SRV record for automatic discovery of connection settings
      Name:
        !Sub
          - '_autodiscover._tcp.${Domain}.'
          - { Domain: !Ref DomainName }
      Type: SRV
      TTL: !Ref TTL 
      ResourceRecords:
      - '0 0 443 mailbox.org.'

